[project]
name = "openfx"
version = "0.1.0"
description = "OpenFX image processing plug-in standard"
readme = "readme.md"
requires-python = ">=3.11"
dependencies = [
    "conan>=2.7.1",
    "pip>=24.0",
]
