# Copyright OpenFX and contributors to the OpenFX project.
# SPDX-License-Identifier: BSD-3-Clause

# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pyyaml>=1.0",
# ]
# ///

import argparse
import difflib
import logging
import os
import re
import sys
from collections import Counter
from pathlib import Path

import yaml
from ofx_prop_utils import (
    get_actions_from_headers,
    get_properties_from_headers,
    get_propsets_from_headers,
    parse_prop_entry,
)

# Set up basic configuration for logging
logging.basicConfig(
    level=logging.INFO,  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
    format="%(levelname)s: %(message)s",  # Format of the log messages
    datefmt="%Y-%m-%d %H:%M:%S",  # Date format
)
log = logging.getLogger(__name__)

# Global vars and config

generated_source_header = """// Copyright OpenFX and contributors to the OpenFX project.
// SPDX-License-Identifier: BSD-3-Clause
// NOTE: This file is auto-generated by gen-props.py. DO NOT EDIT.
"""


def getPropertiesFromFile(path):
    """Get all OpenFX property definitions from C header file.

    Uses a heuristic to identify property #define lines:
    anything starting with '#define' and containing 'Prop' in the name.
    """
    props = set()
    with open(path) as f:
        try:
            lines = f.readlines()
        except UnicodeDecodeError as e:
            log.error(f"error reading {path}: {e}")
            raise
        for l in lines:
            # Detect lines that correspond to a property definition, e.g:
            # #define kOfxPropLala "OfxPropLala"
            splits = l.split()
            if len(splits) < 3:
                continue
            if splits[0] != "#define":
                continue
            # ignore these
            nonProperties = ("kOfxPropertySuite",)
            if splits[1] in nonProperties:
                continue
            # these are props, as well as anything with Prop in the name
            badlyNamedProperties = (
                "kOfxImageEffectFrameVarying",
                "kOfxImageEffectPluginRenderThreadSafety",
            )
            if "Prop" in splits[1] or any(s in splits[1] for s in badlyNamedProperties):
                props.add(splits[1])
    return props


def getPropertiesFromDir(dir):
    """
    Recursively get all property definitions from source files in a dir.
    """

    extensions = {".c", ".h", ".cxx", ".hxx", ".cpp", ".hpp"}

    props = set()
    for root, _dirs, files in os.walk(dir):
        for file in files:
            # Get the file extension
            file_extension = os.path.splitext(file)[1]

            if file_extension in extensions:
                file_path = os.path.join(root, file)
                props |= getPropertiesFromFile(file_path)
    return list(props)


def get_string_defines(dir):
    """Collect every `#define kName "value"` macro and its string value.

    Returns {value: cname}, mapping each string literal to the C macro that
    defines it. Used to resolve enum @propdef values back to the #define they
    name, so we can emit static_asserts and catch typo'd value names. If two
    macros share a value the lexically-first cname wins (either asserts the
    same string, so the choice is immaterial).
    """
    extensions = {".c", ".h", ".cxx", ".hxx", ".cpp", ".hpp"}
    value_to_cname = {}
    pattern = re.compile(r'#define\s+(k\w+)\s+"([^"]+)"')
    for root, _dirs, files in os.walk(dir):
        for file in sorted(files):
            if os.path.splitext(file)[1] not in extensions:
                continue
            with open(os.path.join(root, file)) as f:
                for m in pattern.finditer(f.read()):
                    cname, value = m.group(1), m.group(2)
                    if value not in value_to_cname or cname < value_to_cname[value]:
                        value_to_cname[value] = cname
    return value_to_cname


def enum_value_cname(value, value_to_cname):
    """Resolve an enum @propdef value to the #define that names it.

    Returns the macro cname, or None if the value is an intentional literal
    (e.g. "true"/"false"/"needed") with no backing #define. Raises ValueError
    if the value looks like an OFX constant but has no matching #define, which
    is the typo class of bug this guards against (issue #247).
    """
    if value in value_to_cname:
        return value_to_cname[value]
    if value.startswith(("Ofx", "kOfx")):
        raise ValueError(
            f"enum value '{value}' has no matching #define; "
            f"the @propdef value must equal a macro's string literal"
        )
    return None  # bare literal value, not a #define


def check_default(name, md):
    """Check a @propdef `default:` against the property's type and dimension.

    A default is either one value, which fills every dimension, or one value
    per dimension. An enum default must be one of the declared enum values.
    """
    defaults = md["default"]
    dimension = md["dimension"]
    if len(defaults) != 1 and (dimension == 0 or len(defaults) != dimension):
        raise ValueError(
            f"{name}: default has {len(defaults)} values but the property has "
            f"dimension {dimension}; give one value or one per dimension"
        )
    if isinstance(md["type"], list):
        raise TypeError(
            f"{name}: a multi-typed property cannot have a constant default"
        )
    if md["type"] == "pointer":
        raise ValueError(f"{name}: a pointer property cannot have a default")
    if md["type"] == "enum":
        for v in defaults:
            if v not in md["values"]:
                raise ValueError(
                    f"{name}: default '{v}' is not one of the declared enum values"
                )


def get_def(name: str, defs):
    if name.endswith("_REF"):
        defname = name.replace("_REF", "_DEF")
        return defs[defname]
    else:
        return [name]


def expand_set_props(props_by_set):
    """Expand refs in props_by_sets.
    YAML can't interpolate a list, so we do it here, using
    our own method:
    - A prop set may end with _DEF in which case it's just a definition
      containing a list of prop names.
    - A prop *name* may be <name>_REF which means to interpolate the
      corresponding DEF list into this set's props.
    Returns a new props_by_set with DEFs removed and all lists interpolated.
    """
    # First get all the list defs
    defs = {}
    sets = {}
    for key, value in props_by_set.items():
        if key.endswith("_DEF"):
            defs[key] = value  # should be a list to be interpolated
        else:
            sets[key] = value
    for pset in sets.values():
        if pset.get("props"):
            pset["props"] = [
                item for element in pset["props"] for item in get_def(element, defs)
            ]
    return sets


def actions_to_propsets(props_by_action):
    """Convert action argument property sets to the same format as regular property sets.

    Actions have the structure:
      ActionName:
        inArgs: [prop1, prop2, ...]
        outArgs: [prop3, prop4, ...]

    We convert this to property sets named like:
      ImageEffectActionDescribeInContext_InArgs: {props: [prop1, prop2, ...], write: 'host'}
      ImageEffectActionDescribeInContext_OutArgs: {props: [prop3, prop4, ...], write: 'plugin'}

    The class names are full action names minus "Ofx" prefix, matching C API names.
    """
    result = {}

    for action_name, args in props_by_action.items():
        # Remove "Ofx" prefix to get class-friendly name that matches C API
        # OfxImageEffectActionDescribeInContext -> ImageEffectActionDescribeInContext
        # OfxActionLoad -> ActionLoad
        # OfxInteractActionDraw -> InteractActionDraw
        simple_name = action_name
        simple_name = simple_name.removeprefix("Ofx")  # Remove "Ofx" prefix

        # Generate InArgs property set
        if args.get("inArgs"):
            key = f"{simple_name}_InArgs"
            result[key] = {
                "props": args["inArgs"],
                "write": "host",  # inArgs are written by host, read by plugin
            }

        # Generate OutArgs property set
        if args.get("outArgs"):
            key = f"{simple_name}_OutArgs"
            result[key] = {
                "props": args["outArgs"],
                "write": "plugin",  # outArgs are written by plugin, read by host
            }

    return result


def get_cname(propname, props_metadata):
    """Get the C `#define` name for a property name.

    Look up the special cname in props_metadata, or in the normal
    case just prepend "k".
    """
    return props_metadata[propname].get("cname", "k" + propname)


def get_prop_id(propname):
    """HACK ALERT: a few props' names (string values) start with k.
    Those are also the #define names. If we use those as PropId enum
    values, they'll get expanded into the strings which will lead to
    compile errors. This means the names to be looked up always don't
    have the "k". We could prefix them or something but this should be
    OK."""
    if propname.startswith("k"):
        return propname[1:]
    return propname


def find_stringname(cname, props_metadata):
    """Try to find the actual string corresponding to the C #define name.
    This may be slow; looks through all the metadata for a matching
    "cname", otherwise strips "k".
    """
    for p in props_metadata:
        if props_metadata[p].get("cname") == cname:
            return p
    if cname.startswith("k"):
        return cname[1:]
    return "unknown-stringname-for-" + cname


def find_missing(all_props, props_metadata):
    """Find and print all mismatches between prop defs and inline metadata.

    Checks that every #define kOfx*Prop* in headers has a corresponding
    @propdef block, and vice versa.
    Returns 0 if no errors.
    """
    errs = 0
    for p in sorted(all_props):  # constants from #include files, with "k" prefix
        stringval = find_stringname(p, props_metadata)
        if not props_metadata.get(stringval):
            log.error(f"No @propdef metadata found for {p}")
            errs += 1
    for p in sorted(props_metadata):
        cname = get_cname(p, props_metadata)
        if cname not in all_props:
            log.error(f"No prop definition found for '{p}' in source/include")
            matches = difflib.get_close_matches(p, all_props, 3, 0.9)
            if matches:
                log.info(f" Did you mean: {matches}")
            errs += 1
    return errs


def props_for_set(pset, props_by_set, name_only=True):
    """Generator yielding all props for the given prop set (not used for actions).
    This implements the options override scheme, parsing the prop name etc.
    If not name_only, yields a dict of name and other options.
    """
    if not props_by_set[pset].get("props"):
        return
    # All the default options for this propset. Merged into each prop.
    propset_options = props_by_set[pset].copy()
    propset_options.pop("props", None)
    for p in props_by_set[pset]["props"]:
        name, options = parse_prop_entry(p)
        if name_only:
            yield name
        else:
            yield {**propset_options, **options, "name": name}


def check_props_by_set(props_by_set, props_by_action, props_metadata):
    """Find and print all mismatches between prop set specs, props, and metadata.

    * Each prop name in props_by_set should have a match in props_metadata
    Note that props_by_pset may have multiple levels, e.g. inArgs for an action.
    Returns 0 if no errors.
    """
    errs = 0
    for pset in sorted(props_by_set):
        for p in props_for_set(pset, props_by_set):
            if not props_metadata.get(p):
                log.error(f"No props metadata found for {pset}.{p}")
                errs += 1
    for pset in sorted(props_by_action):
        # For actions, the value of props_by_set[pset] is a dict, each
        # (e.g. inArgs, outArgs) containing a list of props.
        for subset in sorted(props_by_action[pset]):
            if not props_by_action[pset][subset]:
                continue
            for entry in props_by_action[pset][subset]:
                p = parse_prop_entry(entry)[0]
                if not props_metadata.get(p):
                    log.error(f"No props metadata found for action {pset}.{subset}.{p}")
                    errs += 1
    return errs


def check_props_used_by_set(props_by_set, props_by_action, props_metadata):
    """Find and print all mismatches between prop set specs, props, and metadata.

    * Each prop name in props_metadata should be used in at least one set.
    Returns 0 if no errors.
    """
    errs = 0
    for prop in props_metadata:
        found = 0
        for pset in props_by_set:
            for set_prop in props_for_set(pset, props_by_set):
                if set_prop == prop:
                    found += 1
        for pset in props_by_action:
            # inArgs/outArgs
            for subset in sorted(props_by_action[pset]):
                if not props_by_action[pset][subset]:
                    continue
                for entry in props_by_action[pset][subset]:
                    if parse_prop_entry(entry)[0] == prop:
                        found += 1
        if not found and not props_metadata[prop].get("deprecated"):
            log.error(f"Prop {prop} not used in any prop set")
    return errs


def gen_props_metadata(props_metadata, value_to_cname, outfile_path: Path):
    """Generate a header file with metadata for each prop"""
    with open(outfile_path, "w") as outfile:
        outfile.write(generated_source_header)
        outfile.write("""
#pragma once

#include <array>
#include <string_view>

#include <ofxImageEffect.h>
#include <ofxGPURender.h>
#include <ofxColour.h>
#include <ofxDrawSuite.h>
#include <ofxParametricParam.h>
#include <ofxKeySyms.h>
#include <ofxOld.h>

#include "ofxSpan.h"

namespace openfx {
enum class PropType {
   Int,
   Double,
   Enum,
   Bool,
   String,
   Pointer
};

// Each prop has a PropId::<propname> enum, a runtime-accessible PropDef struct, and a compile-time PropTraits<id>.
// PropertyAccessor (openfx/ofxPropsAccess.h) uses them for type-safe property access.

""")
        outfile.write("//Property ID enum for compile-time lookup and type safety\n")
        outfile.write("enum class PropId {\n")
        id = 0
        for p in sorted(props_metadata):
            pname = get_prop_id(p)
            orig_name_msg = ""
            if pname != p:
                orig_name_msg = f" (orig name: {pname})"
            outfile.write(f"  {pname}, // {id}{orig_name_msg}\n")
            id += 1
        outfile.write(f"  NProps // {id}\n")
        outfile.write("}; // PropId\n\n")

        # Property enum values (for enums only)

        outfile.write(
            "// Separate arrays for enum-values for enum props, to keep everything constexpr\n"
        )
        outfile.write("namespace prop_enum_values {\n")
        for p in sorted(props_metadata):
            md = props_metadata[p]
            if md["type"] == "enum":
                values = "{" + ",".join(f'"{v}"' for v in md["values"]) + "}"
                outfile.write(f"inline constexpr std::array {p} =\n  {values};\n")
        outfile.write("} // namespace prop_enum_values\n")

        # Property defaults (for props that declare one), same treatment
        outfile.write(
            "\n// Separate arrays for the spec default of each prop that has one\n"
        )
        outfile.write("namespace prop_default_values {\n")
        for p in sorted(props_metadata):
            defaults = props_metadata[p].get("default")
            if defaults:
                values = "{" + ",".join(f'"{v}"' for v in defaults) + "}"
                outfile.write(f"inline constexpr std::array {p} =\n  {values};\n")
        outfile.write("} // namespace prop_default_values\n")
        # Property definitions

        outfile.write("""

// Property type arrays for spans (generated before PropDef)
namespace prop_type_arrays {
""")
        # Generate type arrays for each property
        for p in sorted(props_metadata):
            md = props_metadata[p]
            types = md.get("type")
            if isinstance(types, str):
                types = (types,)
            prop_type_defs = (
                "{" + ",".join(f"PropType::{t.capitalize()}" for t in types) + "}"
            )
            outfile.write(
                f"inline constexpr PropType {p}_types[] = {prop_type_defs};\n"
            )
        outfile.write("} // namespace prop_type_arrays\n\n")

        outfile.write("""
struct PropDef {
   const char* name;                    // Property name
   openfx::span<const PropType> supportedTypes; // Supported data types
   int dimension;                       // Property dimension (0 means variable/N)
   openfx::span<const char* const> enumValues;  // Valid values for enum properties
   openfx::span<const char* const> defaults{};  // Spec default, as text, one value or one per dimension; empty if none
};

// Array type for storing all PropDefs, indexed by PropId for simplicity
template <typename T, PropId MaxValue = PropId::NProps>
struct PropDefsArray {
    static constexpr size_t Size = static_cast<size_t>(MaxValue);
    std::array<T, Size> data;

    // constexpr T& operator[](PropId index) {
    //   return data[static_cast<size_t>(index)];
    // }

    constexpr const T& operator[](PropId index) const {
        return data[static_cast<size_t>(index)];
    }
    constexpr const T& operator[](size_t index) const {
        return data[index];
    }
};

// Property definitions
inline constexpr PropDefsArray<PropDef> prop_defs = {
  {{
""")

        for p in sorted(props_metadata):
            try:
                # name (id field removed - it was never used)
                prop_def = f'{{ "{p}",\n  '
                md = props_metadata[p]
                types = md.get("type")
                if isinstance(types, str):  # make it always a list
                    types = (types,)
                # types - use span pointing to type array
                type_count = len(types)
                prop_def += f"openfx::span(prop_type_arrays::{p}_types, {type_count}), "
                # dimension
                prop_def += f"{md['dimension']}, "
                # enum values - use span
                if md["type"] == "enum":
                    assert isinstance(md["values"], list)
                    prop_def += f"openfx::span(prop_enum_values::{p}.data(), prop_enum_values::{p}.size())"
                else:
                    prop_def += "openfx::span<const char* const>()"
                # spec default, if any - use span; omitted props take the {} member default
                if md.get("default"):
                    check_default(p, md)
                    prop_def += f",\n  openfx::span(prop_default_values::{p}.data(), prop_default_values::{p}.size())"
                prop_def += "},\n"
                outfile.write(prop_def)
            except Exception as e:
                log.error(f"Error: {p} is missing metadata? {e}")
                raise
        outfile.write(" }}\n};\n\n")

        outfile.write("""
// Look up a property definition by name (prop_defs is sorted by name); nullptr if unknown.
inline constexpr const PropDef* find_prop_def(std::string_view name) {
  size_t lo = 0, hi = prop_defs.Size;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    int cmp = std::string_view(prop_defs[mid].name).compare(name);
    if (cmp == 0) return &prop_defs[mid];
    if (cmp < 0) lo = mid + 1; else hi = mid;
  }
  return nullptr;
}

namespace assertions {
inline constexpr bool prop_defs_sorted = [] {
  for (size_t i = 1; i < prop_defs.Size; ++i)
    if (std::string_view(prop_defs[i - 1].name) >= std::string_view(prop_defs[i].name)) return false;
  return true;
}();
static_assert(prop_defs_sorted, "prop_defs must be sorted by name for find_prop_def");
}  // namespace assertions

//Template specializations for each property
namespace properties {

// Base template struct for property traits
template<PropId id>
struct PropTraits;

#define DEFINE_PROP_TRAITS(id, _type, _is_multitype) \\
template<> \\
struct PropTraits<PropId::id> { \\
    using type = _type; \\
    static constexpr bool is_multitype = _is_multitype; \\
    static constexpr const PropDef& def = prop_defs[PropId::id]; \\
}

""")

        for p in sorted(props_metadata):
            try:
                md = props_metadata[p]
                types = md.get("type")
                if isinstance(types, str):  # make it always a list
                    types = (types,)
                ctypes = {
                    "string": "const char *",
                    "enum": "const char *",
                    "int": "int",
                    "bool": "bool",
                    "double": "double",
                    "pointer": "void *",
                }
                is_multitype_bool = "true" if len(types) > 1 else "false"
                outfile.write(
                    f"DEFINE_PROP_TRAITS({get_prop_id(p)}, {ctypes[types[0]]}, {is_multitype_bool});\n"
                )
            except Exception as e:
                log.error(f"Error: {p} is missing metadata? {e}")
                raise

        outfile.write("} // namespace properties\n\n")
        # Generate static asserts to ensure our constants match the string values
        outfile.write("// Static asserts to check #define names vs. strings\n")
        outfile.write("namespace assertions {\nusing std::string_view;\n\n")
        for p in sorted(props_metadata):
            cname = get_cname(p, props_metadata)
            outfile.write(
                f'static_assert(string_view("{p}") == string_view({cname}));\n'
            )

        # Also assert each enum value equals the #define it names, so a typo'd
        # @propdef value (issue #247) fails to compile. enum_value_cname raises
        # here if a value looks like an OFX constant but names no macro.
        outfile.write("\n// ... and enum values vs their #defines\n")
        for p in sorted(props_metadata):
            md = props_metadata[p]
            if md["type"] != "enum":
                continue
            for v in md["values"]:
                cname = enum_value_cname(v, value_to_cname)
                if cname:
                    outfile.write(
                        f'static_assert(string_view("{v}") == string_view({cname}));\n'
                    )

        outfile.write("} // namespace assertions\n")
        outfile.write("} // namespace openfx\n")


def gen_props_by_set(props_by_set, props_by_action, outfile_path: Path):
    """Generate a header file with definitions of all prop sets, including their props"""
    with open(outfile_path, "w") as outfile:
        outfile.write(generated_source_header)
        outfile.write("""
#pragma once

#include <string>
#include <vector>
#include <map>
#include <array>
#include <ofxImageEffect.h>
#include <ofxGPURender.h>
#include <ofxColour.h>
#include <ofxDialog.h>
#include <ofxDrawSuite.h>
#include <ofxParametricParam.h>
#include <ofxKeySyms.h>
#include "ofxPropsMetadata.h"
// #include <ofxOld.h>

namespace openfx {

struct Prop {
  const char *name;
  const PropDef &def;
  bool host_write;
  bool plugin_write;
  bool host_optional;

  Prop(const char *n, const PropDef &d, bool hw, bool pw, bool ho)
       : name(n), def(d), host_write(hw), plugin_write(pw), host_optional(ho) {}
};

""")
        outfile.write("// Properties for property sets\n")
        outfile.write(
            "inline const std::map<std::string_view, std::vector<Prop>> prop_sets {\n"
        )

        for pset in sorted(props_by_set.keys()):
            propdefs = []
            for p in props_for_set(pset, props_by_set, False):
                host_write = "true" if p["write"] in ("host", "all") else "false"
                plugin_write = "true" if p["write"] in ("plugin", "all") else "false"
                host_optional = "true" if p.get("host_optional") == "true" else "false"
                propdefs.append(
                    f'{{ "{p["name"]}", prop_defs[PropId::{get_prop_id(p["name"])}], {host_write}, {plugin_write}, {host_optional} }}'
                )
            propdefs_str = ",\n   ".join(propdefs)
            outfile.write(f'// {pset}\n{{ "{pset}", {{\n   {propdefs_str} }} }},\n')
        outfile.write("};\n\n")

        actions = sorted(props_by_action.keys())

        outfile.write("// Actions\n")
        outfile.write(
            f"inline const std::array<const char *, {len(actions)}> actions {{\n"
        )
        for pset in actions:
            if not pset.startswith("kOfx"):
                pset = '"' + pset + '"'  # quote if it's not a known constant
            outfile.write(f"  {pset},\n")
        outfile.write("};\n\n")

        outfile.write("// Properties for action args\n")
        outfile.write(
            "inline const std::map<std::array<std::string_view, 2>, std::vector<const char *>> action_props {\n"
        )
        for pset in actions:
            for subset in props_by_action[pset]:
                if not props_by_action[pset][subset]:
                    continue
                propnames = ",\n    ".join(
                    sorted(
                        f'"{parse_prop_entry(p)[0]}"'
                        for p in props_by_action[pset][subset]
                    )
                )
                if not pset.startswith("kOfx"):
                    psetname = '"' + pset + '"'  # quote if it's not a known constant
                else:
                    psetname = pset
                outfile.write(f"// {pset}.{subset}\n")
                outfile.write(
                    f'{{ {{ {psetname}, "{subset}" }},\n  {{ {propnames} }} }},\n'
                )

        outfile.write("};\n\n")

        outfile.write("// Static asserts for standard action names\n")
        for pset in actions:
            if not pset.startswith("Ofx"):
                continue
            outfile.write(
                f'static_assert(std::string_view("{pset}") == std::string_view(k{pset}));\n'
            )

        outfile.write("} // namespace openfx\n")


CPP_KEYWORDS = {
    "default",
    "delete",
    "new",
    "class",
    "int",
    "double",
    "bool",
    "float",
    "char",
    "template",
    "typename",
    "this",
    "operator",
    "return",
    "const",
    "static",
    "using",
}

# The categories of object a property belongs to (kOfx<Category>Prop...),
# longest first. An accessor class already says which object it is for, so
# its method names leave these out; any other category, such as OpenGL,
# qualifies the property and stays.
OBJECT_CATEGORIES = (
    "ImageEffectInstance",
    "ImageEffectHost",
    "ImageEffectPlugin",
    "ImageEffect",
    "ImageClip",
    "Image",
    "ParamHost",
    "Param",
    "Plugin",
    "Interact",
)


def split_category(cname: str) -> tuple[str, str]:
    """Split a property's C #define into its category and the rest of its name.

    kOfxImageEffectPropRenderScale -> ("ImageEffect", "RenderScale"),
    kOfxPropLabel -> ("", "Label"). A name with no "Prop" in it splits after
    its object category: kOfxImageEffectFrameVarying -> ("ImageEffect",
    "FrameVarying").
    """
    name = cname.removeprefix("k").removeprefix("Ofx")
    match = re.match(r"(\w*?)Prop(?=[A-Z])(\w*)", name)
    if match:
        return match.group(1), match.group(2)
    for category in OBJECT_CATEGORIES:
        if name.startswith(category):
            return category, name.removeprefix(category)
    return "", name


def lower_first_word(name: str) -> str:
    """Lower-case the leading word: Label -> label, APIVersion -> apiVersion,
    OpenGLPixelDepth -> openGLPixelDepth, OCIOConfig -> ocioConfig."""
    run = re.match(r"[A-Z]+", name)
    caps = len(run.group()) if run else 0
    if caps == len(name):
        return name.lower()
    if caps > 1:
        return name[: caps - 1].lower() + name[caps - 1 :]
    return name[:1].lower() + name[1:]


def method_name(cname: str, keep_category: bool = False) -> str:
    """The accessor method name for a property, from its C #define."""
    category, rest = split_category(cname)
    if keep_category or category not in ("", *OBJECT_CATEGORIES):
        rest = category + rest
    name = lower_first_word(rest)
    # A method can't be named after a C++ keyword (OfxParamPropDefault -> default)
    return name + "Value" if name in CPP_KEYWORDS else name


def method_names(props: list[str], props_metadata: dict) -> dict[str, str]:
    """Name the accessor methods of one property set's properties.

    Two properties that would share a name (kOfxPropType and
    kOfxParamPropType are both "type") each keep their category instead
    (type and paramType).
    """
    names = {p: method_name(get_cname(p, props_metadata)) for p in props}
    counts = Counter(names.values())
    return {
        p: method_name(get_cname(p, props_metadata), keep_category=True)
        if counts[name] > 1
        else name
        for p, name in names.items()
    }


def gen_propset_accessors(
    props_by_set, props_metadata, outfile_path: Path, for_host=False
):
    """Generate type-safe accessor classes for each property set.

    Args:
        for_host: If True, generate host accessors (setters for host_write, getters for plugin_write).
                  If False, generate plugin accessors (getters for host_write, setters for plugin_write).
    """

    def get_prop_id(propname):
        """Get PropId enum name from property name."""
        if propname.startswith("k"):
            # kOfxParamPropUseHostOverlayHandle -> OfxParamPropUseHostOverlayHandle
            return propname[1:]
        return propname

    def get_cpp_type(prop_def, include_array=True, getter=False):
        """Get the C++ type a setter takes for a property, or with getter, the
        type a getter returns, where a string is a CStringView."""
        types = prop_def.get("type")
        if isinstance(types, str):
            types = [types]

        dimension = prop_def["dimension"]

        # Map OpenFX types to C++ types
        type_map = {
            "string": "const char*",
            "int": "int",
            "double": "double",
            "pointer": "void*",
            "bool": "bool",
            "enum": "const char*",
        }

        cpp_type = type_map.get(types[0], "void*")
        if getter and cpp_type == "const char*":
            cpp_type = "CStringView"

        # If dimension > 1, return array type
        if include_array and dimension > 1:
            return f"std::array<{cpp_type}, {dimension}>"

        return cpp_type

    side = "host" if for_host else "plugin"
    if for_host:
        usage = """//   ImageEffectHost host(hostProps, propSuite);
//   host.setSupportsTiles(true);              // a host-written property
//   EffectDescriptor desc(descriptorProps, propSuite);
//   CStringView label = desc.label();         // a plugin-written one"""
    else:
        usage = """//   EffectDescriptor desc(descriptorProps, propSuite);
//   desc.setLabel("My Effect");               // a plugin-written property
//   ImageEffectHost host(hostProps, propSuite);
//   bool tiles = host.supportsTiles();        // a host-written one"""
    with open(outfile_path, "w") as outfile:
        outfile.write(generated_source_header)
        target = side.upper()
        outfile.write(f"""
#pragma once

#include <array>
#include <vector>
#include "openfx/ofxPropsAccess.h"
#include "openfx/ofxPropsMetadata.h"

namespace openfx::{side}::propsets {{

// Type-safe property set accessor classes for {target}S
//
// These wrapper classes provide convenient, type-safe access to property sets.
// - For plugins: getters for host-written properties, setters for plugin-written properties
// - For hosts: setters for host-written properties, getters for plugin-written properties
//
// Each property's methods follow a comment giving the C #define of the
// property they read or write.
//
// Usage:
{usage}
//
// An existing PropertyAccessor works just as well:
//   PropertyAccessor accessor(descriptorProps, propSuite);
//   EffectDescriptor desc(accessor);
//
// Either way the object is a self-contained value holding its own
// PropertyAccessor, so it can be copied and returned freely.

// Base class for property set accessors
class PropertySetAccessor {{
protected:
    PropertyAccessor props_;
public:
    explicit PropertySetAccessor(PropertyAccessor props) : props_(props) {{}}
    PropertySetAccessor(OfxPropertySetHandle handle, const OfxPropertySuiteV1* suite)
        : props_(handle, suite) {{}}
    PropertySetAccessor(OfxPropertySetHandle handle, const SuiteContainer& suites)
        : props_(handle, suites) {{}}

    // The underlying PropertyAccessor, for properties these classes do not cover
    PropertyAccessor& props() {{ return props_; }}
    const PropertyAccessor& props() const {{ return props_; }}
}};

""")

        # Generate a class for each property set
        for pset_name in sorted(props_by_set.keys()):
            # Derive class name from property set name
            class_name = pset_name.replace(" ", "")

            outfile.write(f"// Property set accessor for: {pset_name}\n")
            outfile.write(f"class {class_name} : public PropertySetAccessor {{\n")
            outfile.write("public:\n")
            outfile.write("    using PropertySetAccessor::PropertySetAccessor;\n\n")

            set_props = dict.fromkeys(
                p for p in props_for_set(pset_name, props_by_set) if p in props_metadata
            )
            names = method_names(list(set_props), props_metadata)
            generated_methods = {}  # method name -> property

            # Generate methods for each property
            for prop in props_for_set(pset_name, props_by_set, name_only=False):
                propname = prop["name"]
                write_access = prop["write"]
                is_host_optional = prop.get("host_optional") == "true"

                # Get property metadata
                if propname not in props_metadata:
                    continue

                prop_def = props_metadata[propname]
                method = names[propname]
                prop_id = get_prop_id(propname)

                # A property listed twice gets its methods once; two properties
                # that still share a name with their categories are reported.
                if method in generated_methods:
                    if generated_methods[method] != propname:
                        print(
                            f"WARNING: {class_name}: {propname} and {generated_methods[method]} "
                            f"both map to method {method}; skipping {propname}",
                            file=sys.stderr,
                        )
                    continue
                generated_methods[method] = propname

                # A property a host may leave out is soft by default: its
                # absence is no error, though any other failure still is
                error_default = "false" if is_host_optional else "true"

                # Check if this is a multi-type property
                types = prop_def.get("type")
                if isinstance(types, str):
                    types = [types]
                is_multitype = len(types) > 1

                dimension = prop_def["dimension"]
                cpp_type = (
                    get_cpp_type(prop_def, include_array=False)
                    if not is_multitype
                    else None
                )

                # Determine what to generate based on for_host flag
                # For plugins: getters for host-written, setters for plugin-written
                # For hosts: setters for host-written, getters for plugin-written
                generate_getter = False
                generate_setter = False

                if for_host:
                    # Host accessors: host sets, host reads plugin-written
                    if write_access in ("host", "all"):
                        generate_setter = True
                    if write_access in ("plugin", "all"):
                        generate_getter = True
                else:
                    # Plugin accessors: plugin reads host-written, plugin sets
                    if write_access in ("host", "all"):
                        generate_getter = True
                    if write_access in ("plugin", "all"):
                        generate_setter = True

                outfile.write(f"    // {get_cname(propname, props_metadata)}\n")

                # Generate getter
                if generate_getter:
                    if is_multitype:
                        # Multi-type property - generate templated getter
                        outfile.write(
                            f"    // Multi-type property (supports: {', '.join(types)})\n"
                        )
                        outfile.write("    template<typename T>\n")
                        if dimension == 1:
                            # Dimension 1: exactly one value, no index needed
                            outfile.write(
                                f"    T {method}(bool error_if_missing = {error_default}) const {{\n"
                            )
                            outfile.write(
                                f"        return props_.get<PropId::{prop_id}, T>(0, error_if_missing);\n"
                            )
                        else:
                            # Dimension 0 or > 1: include index parameter
                            outfile.write(
                                f"    T {method}(int index = 0, bool error_if_missing = {error_default}) const {{\n"
                            )
                            outfile.write(
                                f"        return props_.get<PropId::{prop_id}, T>(index, error_if_missing);\n"
                            )
                        outfile.write("    }\n\n")

                        # Also provide getAll for multi-type (returns vector)
                        if dimension != 1:  # dimension 0 or > 1
                            outfile.write("    template<typename T>\n")
                            outfile.write(
                                f"    std::vector<T> {method}All(bool error_if_missing = {error_default}) const {{\n"
                            )
                            outfile.write(
                                f"        return props_.getAllTyped<PropId::{prop_id}, T>(error_if_missing);\n"
                            )
                            outfile.write("    }\n\n")
                    else:
                        # Single-type property
                        value_type = get_cpp_type(
                            prop_def, include_array=False, getter=True
                        )
                        if dimension == 1:
                            # Dimension 1: exactly one value, no index needed
                            outfile.write(
                                f"    {value_type} {method}(bool error_if_missing = {error_default}) const {{\n"
                            )
                            outfile.write(
                                f"        return props_.get<PropId::{prop_id}>(0, error_if_missing);\n"
                            )
                            outfile.write("    }\n\n")
                        elif dimension == 0:
                            # Dimension 0: variable dimension, include index
                            outfile.write(
                                f"    {value_type} {method}(int index = 0, bool error_if_missing = {error_default}) const {{\n"
                            )
                            outfile.write(
                                f"        return props_.get<PropId::{prop_id}>(index, error_if_missing);\n"
                            )
                            outfile.write("    }\n\n")
                        else:
                            # Dimension > 1: array getter
                            array_type = get_cpp_type(
                                prop_def, include_array=True, getter=True
                            )
                            outfile.write(
                                f"    {array_type} {method}(bool error_if_missing = {error_default}) const {{\n"
                            )
                            outfile.write(
                                f"        return props_.getAll<PropId::{prop_id}>(error_if_missing);\n"
                            )
                            outfile.write("    }\n\n")

                # Generate setter
                if generate_setter:
                    setter_name = "set" + method[0].upper() + method[1:]

                    if is_multitype:
                        # Multi-type property - generate templated setter
                        outfile.write(
                            f"    // Multi-type property (supports: {', '.join(types)})\n"
                        )
                        outfile.write("    template<typename T>\n")
                        if dimension == 1:
                            # Dimension 1: exactly one value, no index needed
                            outfile.write(
                                f"    {class_name}& {setter_name}(T value, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.set<PropId::{prop_id}, T>(value, 0, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                        else:
                            # Dimension 0 or > 1: include index parameter
                            outfile.write(
                                f"    {class_name}& {setter_name}(T value, int index = 0, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.set<PropId::{prop_id}, T>(value, index, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                        outfile.write("    }\n\n")

                        # Also provide setAll for multi-type
                        if dimension != 1:  # dimension 0 or > 1
                            outfile.write(
                                "    // Set all values from a container (vector, array, span, etc.)\n"
                            )
                            outfile.write(
                                "    // SFINAE: only enabled for container types (not scalars)\n"
                            )
                            outfile.write(
                                "    template<typename T, typename Container,\n"
                            )
                            outfile.write(
                                "             typename = std::enable_if_t<!std::is_arithmetic_v<Container> && !std::is_pointer_v<Container>>>\n"
                            )
                            outfile.write(
                                f"    {class_name}& {setter_name}(const Container& values, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.setAllTyped<PropId::{prop_id}, T>(values, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")

                            # Also provide initializer_list overload for multi-type
                            outfile.write(
                                "    // Set all values from an initializer list (e.g., {1, 2, 3})\n"
                            )
                            outfile.write("    template<typename T>\n")
                            outfile.write(
                                f"    {class_name}& {setter_name}(std::initializer_list<T> values, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.setAllTyped<PropId::{prop_id}, T>(values, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")
                    else:
                        # Single-type property
                        if dimension == 1:
                            # Dimension 1: exactly one value, no index needed
                            outfile.write(
                                f"    {class_name}& {setter_name}({cpp_type} value, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.set<PropId::{prop_id}>(value, 0, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")
                        elif dimension == 0:
                            # Dimension 0: variable dimension, include index
                            outfile.write(
                                f"    {class_name}& {setter_name}({cpp_type} value, int index = 0, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.set<PropId::{prop_id}>(value, index, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")

                            # Also generate a container/span setter for dimension 0
                            outfile.write(
                                "    // Set all values from a container (vector, array, span, etc.)\n"
                            )
                            outfile.write(
                                "    // SFINAE: only enabled for container types (not scalars)\n"
                            )
                            outfile.write("    template<typename Container,\n")
                            outfile.write(
                                "             typename = std::enable_if_t<!std::is_arithmetic_v<Container> && !std::is_pointer_v<Container>>>\n"
                            )
                            outfile.write(
                                f"    {class_name}& {setter_name}(const Container& values, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.setAll<PropId::{prop_id}>(values, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")

                            # Also generate an initializer_list overload for dimension 0
                            outfile.write(
                                "    // Set all values from an initializer list (e.g., {1, 2, 3})\n"
                            )
                            outfile.write(
                                f"    {class_name}& {setter_name}(std::initializer_list<{cpp_type}> values, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.setAll<PropId::{prop_id}>(values, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")
                        else:
                            # Dimension > 1: array setter
                            array_type = get_cpp_type(prop_def, include_array=True)
                            outfile.write(
                                f"    {class_name}& {setter_name}(const {array_type}& values, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.setAll<PropId::{prop_id}>(values, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")

                            # Also generate an initializer_list overload for dimension > 1
                            outfile.write(
                                "    // Set all values from an initializer list (e.g., {1, 2})\n"
                            )
                            outfile.write(
                                f"    {class_name}& {setter_name}(std::initializer_list<{cpp_type}> values, bool error_if_missing = {error_default}) {{\n"
                            )
                            outfile.write(
                                f"        props_.setAll<PropId::{prop_id}>(values, error_if_missing);\n"
                            )
                            outfile.write("        return *this;\n")
                            outfile.write("    }\n\n")

            outfile.write("};\n\n")

        outfile.write(f"}} // namespace openfx::{side}::propsets\n")


def host_enum_values(name: str, md: dict) -> list[str]:
    """The declared values of a host-defined enum property, checked to be text."""
    values = md.get("values")
    if not values:
        raise ValueError(f"{name}: an enum property needs a list of values")
    for v in values:
        if not isinstance(v, str):
            raise TypeError(f"{name}: enum value {v!r} is not a string; quote it")
    return values


def gen_host_metadata(props_metadata: dict, outfile_path: Path, namespace: str) -> None:
    """Generate a metadata header for host-specific properties.

    This generates a self-contained header that references openfx::PropType
    and openfx::PropDef from the main OpenFX metadata, but defines its own
    PropId enum, prop_defs array, and PropTraits in the given namespace, and
    a C name macro per property (k<key>, or the property's `cname`).
    """
    ctypes = {
        "string": "const char*",
        "enum": "const char*",
        "int": "int",
        "bool": "bool",
        "double": "double",
        "pointer": "void*",
    }
    cnames = {p: md.get("cname", "k" + p) for p, md in props_metadata.items()}

    with open(outfile_path, "w") as outfile:
        outfile.write(generated_source_header)
        outfile.write("""
#pragma once

#include <array>
#include <string_view>
#include <openfx/ofxPropsMetadata.h>
#include <openfx/ofxSpan.h>

// The C name of each property, as the OFX headers give theirs, so C and C++
// code use the same constant. The host's own C header may define them first.
""")
        for p, md in props_metadata.items():
            name = md.get("name", p)
            outfile.write(
                f'#ifndef {cnames[p]}\n#define {cnames[p]} "{name}"\n#endif\n'
            )
        outfile.write(f"""
// ============== Host-specific property definitions for {namespace} ==============

namespace {namespace} {{

// Property ID enum for compile-time lookup and type safety
enum class PropId {{
""")
        props = list(props_metadata.keys())
        for i, p in enumerate(props):
            md = props_metadata[p]
            desc = md.get("description", "")
            outfile.write(f"  {p} = {i},  // {desc}\n")
        outfile.write("};\n\n")

        outfile.write("namespace properties {\n\n")

        # Type arrays
        for p in props:
            md = props_metadata[p]
            ptype = md.get("type")
            if isinstance(ptype, str):
                ptype = [ptype]
            type_list = ", ".join(f"openfx::PropType::{t.capitalize()}" for t in ptype)
            outfile.write(
                f"inline constexpr openfx::PropType {p}_types[] = {{{type_list}}};\n"
            )
            if "enum" in ptype:
                values = ", ".join(f'"{v}"' for v in host_enum_values(p, md))
                outfile.write(
                    f"inline constexpr const char* {p}_values[] = {{{values}}};\n"
                )
        outfile.write("\n")

        # prop_defs array
        outfile.write("inline constexpr openfx::PropDef prop_defs[] = {\n")
        for p in props:
            md = props_metadata[p]
            name = md.get("name", p)
            dimension = md.get("dimension", 1)
            ptype = md.get("type")
            if isinstance(ptype, str):
                ptype = [ptype]
            desc = md.get("description", "")
            if "enum" in ptype:
                values = f"openfx::span({p}_values, {len(md['values'])})"
            else:
                values = "openfx::span<const char* const>()"
            outfile.write(f'  // {p} - "{desc}"\n')
            outfile.write(f'  {{ "{name}",\n')
            outfile.write(
                f"    openfx::span({p}_types, {len(ptype)}), {dimension}, {values} }},\n"
            )
        outfile.write("};\n\n")

        outfile.write("// A C name defined before this header must agree with it\n")
        for p in props:
            name = props_metadata[p].get("name", p)
            outfile.write(
                f'static_assert(std::string_view({cnames[p]}) == "{name}");\n'
            )
        outfile.write("\n")

        # PropTraits
        outfile.write("// Base template (leave undefined - specializations required)\n")
        outfile.write("template<PropId id>\n")
        outfile.write("struct PropTraits;\n\n")

        for p in props:
            md = props_metadata[p]
            ptype = md.get("type")
            if isinstance(ptype, str):
                ptype = [ptype]
            dimension = md.get("dimension", 1)
            cpp_type = ctypes.get(ptype[0], "void*")
            is_multitype = "true" if len(ptype) > 1 else "false"
            outfile.write("template<>\n")
            outfile.write(f"struct PropTraits<PropId::{p}> {{\n")
            outfile.write(f"  using type = {cpp_type};\n")
            outfile.write(f"  static constexpr bool is_multitype = {is_multitype};\n")
            outfile.write(f"  static constexpr int dimension = {dimension};\n")
            outfile.write(
                f"  static constexpr const openfx::PropDef& def = prop_defs[static_cast<size_t>(PropId::{p})];\n"
            )
            outfile.write("};\n\n")

        outfile.write("}  // namespace properties\n\n")

        # ADL helper
        outfile.write("// ADL helper for openfx::PropertyAccessor lookup\n")
        outfile.write("template<PropId id>\n")
        outfile.write(
            "properties::PropTraits<id> prop_traits_helper(std::integral_constant<PropId, id>);\n\n"
        )

        outfile.write(f"}}  // namespace {namespace}\n")


def main(args):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    include_dir = Path(script_dir).parent / "include"
    all_props = getPropertiesFromDir(include_dir)
    log.info(f'Got {len(all_props)} props from "include" dir')

    # All data is now extracted from inline blocks in headers
    props_by_set = expand_set_props(get_propsets_from_headers(include_dir))
    props_by_action = get_actions_from_headers(include_dir)
    props_metadata = get_properties_from_headers(include_dir)
    value_to_cname = get_string_defines(include_dir)

    # Convert action argument property sets to the same format as regular property sets
    action_propsets = actions_to_propsets(props_by_action)

    # Merge action property sets with regular property sets for accessor generation
    all_propsets = {**props_by_set, **action_propsets}

    if args.verbose:
        print(
            "\n=== Checking props: should map 1:1 to props found in source/header files"
        )
    errs = find_missing(all_props, props_metadata)
    if not errs and args.verbose:
        print(" ✔️ ALL OK")

    if args.verbose:
        print("\n=== Checking: every prop in a set should have metadata")
    errs = check_props_by_set(props_by_set, props_by_action, props_metadata)
    if not errs and args.verbose:
        print(" ✔️ ALL OK")

    if args.verbose:
        print("\n=== Checking: every prop should be used in at least one set")
    errs = check_props_used_by_set(props_by_set, props_by_action, props_metadata)
    if not errs and args.verbose:
        print(" ✔️ ALL OK")

    if args.verbose:
        print(f"=== Generating {args.props_metadata}")
    gen_props_metadata(props_metadata, value_to_cname, dest_path / args.props_metadata)

    if args.verbose:
        print(f"=== Generating props by set header {args.props_by_set}")
    gen_props_by_set(props_by_set, props_by_action, dest_path / args.props_by_set)

    if args.verbose:
        print(
            f"=== Generating property set accessor classes for plugins: {args.propset_accessors}"
        )
    gen_propset_accessors(
        all_propsets, props_metadata, dest_path / args.propset_accessors, for_host=False
    )

    if args.verbose:
        print(
            f"=== Generating property set accessor classes for hosts: {args.propset_accessors_host}"
        )
    gen_propset_accessors(
        all_propsets,
        props_metadata,
        dest_path / args.propset_accessors_host,
        for_host=True,
    )


def host_metadata_main(args):
    """Generate metadata header from a host-specific YAML file."""
    with open(args.input, "r") as f:
        props_data = yaml.safe_load(f)
    props_metadata = props_data["properties"]

    if args.verbose:
        print(
            f"=== Generating host metadata: {args.output} (namespace: {args.namespace})"
        )
    gen_host_metadata(props_metadata, Path(args.output), args.namespace)
    if args.verbose:
        print(f" ✔️ Generated {args.output} with {len(props_metadata)} properties")


if __name__ == "__main__":
    script_dir = os.path.dirname(os.path.abspath(__file__))
    dest_path = Path(script_dir).parent / "openfx-cpp/include/openfx"
    parser = argparse.ArgumentParser(
        description="Check OpenFX properties and generate ancillary data structures",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Enable verbose mode"
    )

    subparsers = parser.add_subparsers(dest="command")

    # Default command (no subcommand): generate all OpenFX metadata
    parser.add_argument(
        "--props-metadata",
        default=dest_path / "ofxPropsMetadata.h",
        help="Generate property metadata into this file",
    )
    parser.add_argument(
        "--props-by-set",
        default=dest_path / "ofxPropsBySet.h",
        help="Generate props by set metadata into this file",
    )
    parser.add_argument(
        "--propset-accessors",
        default=dest_path / "plugin" / "ofxPropSetAccessors.h",
        help="Generate property set accessor classes for plugins into this file",
    )
    parser.add_argument(
        "--propset-accessors-host",
        default=dest_path / "host" / "ofxPropSetAccessors.h",
        help="Generate property set accessor classes for hosts into this file",
    )

    # Subcommand: host-metadata
    host_parser = subparsers.add_parser(
        "host-metadata", help="Generate metadata header from a host-specific YAML file"
    )
    host_parser.add_argument("input", help="Path to host-specific YAML properties file")
    host_parser.add_argument(
        "-o", "--output", required=True, help="Output header file path"
    )
    host_parser.add_argument(
        "-n", "--namespace", required=True, help="C++ namespace for the generated code"
    )

    args = parser.parse_args()

    if args.command == "host-metadata":
        host_metadata_main(args)
    else:
        main(args)
